"""Guards the schema: models and migrations must never drift apart."""

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from tests.integration.conftest import alembic_config

pytestmark = pytest.mark.integration


def test_models_match_migrations():
    """Fails if a model was changed without a matching migration.

    Fix: make migration m="describe the change", review the file, commit it.
    """
    try:
        command.check(alembic_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"models and migrations differ; create a migration:\n{exc}")


def test_downgrade_and_upgrade_round_trip():
    """Every migration must be reversible, so a bad deploy can be rolled back."""
    cfg = alembic_config()
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
