"""initial schema

Baseline for every table that existed while the app used create_all.

Hand edits on top of autogenerate:
  - the pgvector extension is created first (knowledge_articles.embedding)
  - enum types are created once up front with create_type=False on the
    columns, because category_enum is shared by two tables and autogenerate
    would try to create it twice
  - downgrade drops the enum types as well as the tables

Revision ID: 0001
Revises:
Create Date: 2026-09-30 09:01:04.703644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (Vector columns render as pgvector.sqlalchemy.Vector)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum types. SQLAlchemy stores the member *names* (e.g. 'AGENT'), which is
# what create_all produced, so existing databases stay compatible.
CATEGORY = postgresql.ENUM(
    'CREDIT_REPORT_DISPUTE', 'REPORT_MISUSE', 'DEBT_COLLECTION',
    'CARDS_AND_ACCOUNTS', 'MORTGAGE', 'CONSUMER_LOANS',
    name='category_enum', create_type=False,
)
USER_ROLE = postgresql.ENUM('AGENT', 'MANAGER', 'ADMIN', name='user_role', create_type=False)
COMPLAINT_STATUS = postgresql.ENUM(
    'NEW', 'IN_REVIEW', 'AWAITING_CUSTOMER', 'RESOLVED', 'ESCALATED',
    name='complaint_status', create_type=False,
)
ANALYSIS_STATUS = postgresql.ENUM(
    'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status', create_type=False,
)
SENTIMENT = postgresql.ENUM('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment_enum', create_type=False)
PRIORITY = postgresql.ENUM('P0', 'P1', 'P2', 'P3', name='priority_enum', create_type=False)

ENUMS = (CATEGORY, USER_ROLE, COMPLAINT_STATUS, ANALYSIS_STATUS, SENTIMENT, PRIORITY)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    bind = op.get_bind()
    for enum in ENUMS:
        enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('knowledge_articles',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', CATEGORY, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', USER_ROLE, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('complaints',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('customer_ref', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('redacted_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', COMPLAINT_STATUS, nullable=False),
    sa.Column('analysis_status', ANALYSIS_STATUS, nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(raw_text) BETWEEN 20 AND 5000', name='chk_text_len'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of'], ['complaints.complaint_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index('idx_complaints_hash', 'complaints', ['text_hash', 'customer_ref'], unique=False)
    op.create_index('idx_complaints_status', 'complaints', ['status'], unique=False)
    op.create_index('idx_complaints_submitted', 'complaints', ['submitted_at'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('field_corrected', sa.String(length=32), nullable=False),
    sa.Column('original_value', sa.String(length=64), nullable=False),
    sa.Column('corrected_value', sa.String(length=64), nullable=False),
    sa.Column('corrected_by', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('generated_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_resolution', sa.Text(), nullable=True),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('cited_article_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('was_edited', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id'),
    sa.UniqueConstraint('complaint_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('category', CATEGORY, nullable=False),
    sa.Column('category_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sentiment_label', SENTIMENT, nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('priority_bucket', PRIORITY, nullable=False),
    sa.Column('priority_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('inference_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('complaint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('generated_content')
    op.drop_table('feedback')
    op.drop_index('idx_complaints_submitted', table_name='complaints')
    op.drop_index('idx_complaints_status', table_name='complaints')
    op.drop_index('idx_complaints_hash', table_name='complaints')
    op.drop_table('complaints')
    op.drop_table('users')
    op.drop_table('knowledge_articles')
    op.drop_table('audit_log')
    bind = op.get_bind()
    for enum in reversed(ENUMS):
        enum.drop(bind, checkfirst=True)
    # The vector extension is left installed; dropping it needs superuser
    # rights and nothing else depends on it being absent.
    # ### end Alembic commands ###
